spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: gmmx-backend
  jpa:
    properties:
      hibernate:
        format_sql: true
        filter:
          tenantFilter:
            condition: tenant_id = :tenantId
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080
  address: 0.0.0.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always