ALTER TABLE tenants 
ADD COLUMN attendance_mode VARCHAR(20) DEFAULT 'MANUAL',
ADD COLUMN latitude DOUBLE PRECISION,
ADD COLUMN longitude DOUBLE PRECISION,
ADD COLUMN attendance_radius DOUBLE PRECISION DEFAULT 500.0,
ADD COLUMN qr_secret TEXT;
